name: "InventorySharer"
author: TheTealViper
version: "1.18.1.a.1"
api-version: 1.18
description: "Allow players to share their inventories in a clickable chat message"
main: me.TheTealViper.inventorysharer.InventorySharer